.PHONY: clean upgrade format test build upgrade

go  := ${shell which go}

clean:
	${go} clean
	cd demo/build_go_rocksdb && ${go} clean
	cd demo/lang_bench && ${go} clean
	cd demo/map_sort_collection && ${go} clean
	cd demo/mcp_sqlite && ${go} clean
upgrade:
	${go} get -t -u all && ${go} mod tidy
	cd demo/build_go_rocksdb && ${go} get -t -u all && ${go} mod tidy
	cd demo/lang_bench && ${go} get -t -u all && ${go} mod tidy
	cd demo/map_sort_collection && ${go} get -t -u all && ${go} mod tidy
	cd demo/mcp_sqlite && ${go} get -t -u all && ${go} mod tidy
format:
	${go} fmt ./...
	cd demo/build_go_rocksdb && ${go} fmt ./...
	cd demo/lang_bench && ${go} fmt ./...
	cd demo/map_sort_collection && ${go} fmt ./...
	cd demo/mcp_sqlite && ${go} fmt ./...
test:
	${go} test ./...
	# cd demo/build_go_rocksdb && ${go} test ./...
	cd demo/lang_bench && ${go} test ./...
	cd demo/map_sort_collection && ${go} test ./...
build:
	${go} build ./...
	# cd demo/build_go_rocksdb && ${go} build ./...
	cd demo/lang_bench && ${go} build ./...
	cd demo/map_sort_collection && ${go} build ./...
	cd demo/mcp_sqlite && ${go} build ./...
install:
	${go} install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
lint:
	golangci-lint run